const pool=require('../config/database');
const select=`SELECT cp.*,p.first_name,p.last_name,t.name team_name FROM coverage_players cp JOIN players p ON p.id=cp.player_id JOIN teams t ON t.id=cp.team_id`;
async function findAllPlayers(){return (await pool.query('SELECT * FROM players ORDER BY last_name,first_name')).rows;}
async function search(q=''){return (await pool.query(`SELECT p.*,COALESCE(string_agg(t.name||' — '||d.name,', '),'Sin plantel') rosters FROM players p LEFT JOIN roster_memberships rm ON rm.player_id=p.id AND rm.active LEFT JOIN teams t ON t.id=rm.team_id LEFT JOIN divisions d ON d.id=rm.division_id WHERE lower(p.first_name||' '||p.last_name) LIKE lower($1) GROUP BY p.id ORDER BY p.last_name LIMIT 30`,[`%${q.trim()}%`])).rows;}
async function createPlayer(first,last){return (await pool.query(`INSERT INTO players(first_name,last_name) VALUES($1,$2) RETURNING *`,[first.trim(),last.trim()])).rows[0];}
async function history(id){return (await pool.query(`SELECT p.*,COUNT(cp.id)::int coverages,COALESCE(SUM(cp.photos_taken),0)::int total_photos,COUNT(cp.id) FILTER(WHERE cp.purchase_type!='none')::int purchases,COALESCE(SUM(cp.agreed_price) FILTER(WHERE cp.purchase_type!='none'),0) historical_amount,MAX(c.event_date) last_coverage FROM players p LEFT JOIN coverage_players cp ON cp.player_id=p.id LEFT JOIN coverages c ON c.id=cp.coverage_id WHERE p.id=$1 GROUP BY p.id`,[id])).rows[0];}
async function findForCoverage(id){return (await pool.query(`${select} WHERE cp.coverage_id=$1 ORDER BY t.name,p.last_name,p.first_name`,[id])).rows;}
async function findEntry(id){return (await pool.query(`${select} WHERE cp.id=$1`,[id])).rows[0];}
async function create(coverageId,data){const client=await pool.connect();try{await client.query('BEGIN');let playerId=data.player_id;if(!playerId){const p=await client.query(`INSERT INTO players(first_name,last_name) VALUES($1,$2) ON CONFLICT(first_name,last_name) DO UPDATE SET first_name=EXCLUDED.first_name RETURNING id`,[data.first_name,data.last_name]);playerId=p.rows[0].id;}const r=await client.query(`INSERT INTO coverage_players(coverage_id,player_id,team_id,jersey_number,photos_taken,requested_photos,purchased_photos,photos_purchased,agreed_price,status,notes,purchase_type,player_payment_status,is_additional_sale) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[coverageId,playerId,...values(data)]);await client.query('COMMIT');return r.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function update(id,data){return (await pool.query(`UPDATE coverage_players SET team_id=$1,jersey_number=$2,photos_taken=$3,requested_photos=$4,purchased_photos=$5,photos_purchased=$6,agreed_price=$7,status=$8,notes=$9,purchase_type=$10,player_payment_status=$11,is_additional_sale=$12,updated_at=NOW() WHERE id=$13 RETURNING *`,[...values(data),id])).rows[0];}
async function quickUpdate(id,field){if(field==='requested_photos')return (await pool.query('UPDATE coverage_players SET requested_photos=NOT requested_photos,updated_at=NOW() WHERE id=$1 RETURNING *',[id])).rows[0];if(field==='purchased_photos')return (await pool.query(`UPDATE coverage_players SET purchased_photos=NOT purchased_photos,photos_taken=CASE WHEN NOT purchased_photos THEN GREATEST(photos_taken,1) ELSE photos_taken END,photos_purchased=CASE WHEN NOT purchased_photos THEN GREATEST(photos_purchased,1) ELSE photos_purchased END,updated_at=NOW() WHERE id=$1 RETURNING *`,[id])).rows[0];return null;}
async function remove(id){return (await pool.query('DELETE FROM coverage_players WHERE id=$1 RETURNING id',[id])).rowCount>0;}
async function reassignTeam(coverageId,oldTeamId,newTeamId){if(oldTeamId&&newTeamId&&oldTeamId!==newTeamId)await pool.query('UPDATE coverage_players SET team_id=$1,updated_at=NOW() WHERE coverage_id=$2 AND team_id=$3',[newTeamId,coverageId,oldTeamId]);}
async function summary(coverageId){return (await pool.query(`SELECT COUNT(*) FILTER(WHERE photos_taken>0)::int players_photographed,COALESCE(SUM(photos_taken),0)::int photos_taken,COUNT(*) FILTER(WHERE requested_photos OR status IN ('Consultó','Interesado'))::int inquiries,COUNT(*) FILTER(WHERE purchased_photos)::int buyers,COALESCE(SUM(photos_purchased),0)::int photos_sold,COALESCE(SUM(agreed_price) FILTER(WHERE purchased_photos),0) amount_sold FROM coverage_players WHERE coverage_id=$1`,[coverageId])).rows[0];}
function values(d){return [d.team_id,d.jersey_number,d.photos_taken,d.requested_photos,d.purchased_photos,d.photos_purchased,d.agreed_price,d.status,d.notes,d.purchase_type,d.player_payment_status,d.is_additional_sale];}
module.exports={findAllPlayers,search,createPlayer,history,findForCoverage,findEntry,create,update,quickUpdate,remove,reassignTeam,summary};
