const coverages=require('../repositories/coverageRepository'); const clients=require('../repositories/clientRepository'); const teams=require('../repositories/teamRepository'); const rosters=require('../repositories/rosterRepository'); const players=require('../repositories/playerRepository'); const sales=require('../repositories/salesRepository'); const {pricing}=require('../services/pricingService'); const {validateCoverage}=require('../services/validationService'); const constants=require('../models/constants');
async function locals(coverage,errors=[]){return {coverage,clients:await clients.findAll(),teams:await teams.findAll(),divisions:await rosters.divisions(),errors,...constants};}
async function list(req,res){res.render('coverages/index',{title:'Coberturas',coverages:await coverages.findAll(),message:req.query.message});}
async function detail(req,res){const coverage=await coverages.findById(req.params.id); if(!coverage)return res.sendStatus(404); const entries=await players.findForCoverage(coverage.id);const teamSales=await sales.teamSales(coverage.id); res.render('coverages/detail',{title:coverage.event_name,coverage,homePlayers:entries.filter(p=>p.team_id===coverage.home_team_id),awayPlayers:entries.filter(p=>p.team_id===coverage.away_team_id),summary:await players.summary(coverage.id),financials:await sales.coverageFinancials(coverage.id),teamSales,pricing,message:req.query.message});}
async function newForm(req,res){res.render('coverages/form',{title:'Nueva cobertura',...await locals({})});}
async function editForm(req,res){const coverage=await coverages.findById(req.params.id); if(!coverage)return res.sendStatus(404); res.render('coverages/form',{title:'Editar cobertura',...await locals(coverage)});}
async function create(req,res){const {data,errors}=validateCoverage(req.body); if(errors.length)return res.status(422).render('coverages/form',{title:'Nueva cobertura',...await locals(data,errors)});const c=await coverages.create(data);const year=new Date(data.event_date).getUTCFullYear();await rosters.populateCoverage(c.id,data.home_team_id,data.home_division_id,year);await rosters.populateCoverage(c.id,data.away_team_id,data.away_division_id,year);res.redirect(`/coverages/${c.id}?message=Planteles cargados automáticamente`);}
async function update(req,res){const {data,errors}=validateCoverage(req.body); data.id=req.params.id; if(errors.length)return res.status(422).render('coverages/form',{title:'Editar cobertura',...await locals(data,errors)}); const previous=await coverages.findById(req.params.id);if(!previous)return res.sendStatus(404);await coverages.update(req.params.id,data);await players.reassignTeam(previous.id,previous.home_team_id,data.home_team_id);await players.reassignTeam(previous.id,previous.away_team_id,data.away_team_id);res.redirect(`/coverages/${req.params.id}`);}
async function remove(req,res){if(!await coverages.remove(req.params.id))return res.sendStatus(404); res.redirect('/coverages?message=Cobertura eliminada');}
module.exports={list,detail,newForm,editForm,create,update,remove};
